version: '3.8'

services:
  backend:
    build: .                    
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://jharavi0605_db_user:google2025@cluster0.4gnqauq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
